// Code generated by MockGen. DO NOT EDIT.
// Source: o365mbx/filehandler (interfaces: FileHandlerInterface)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_filehandler.go -package=mocks o365mbx/filehandler FileHandlerInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	filehandler "o365mbx/filehandler"
	o365client "o365mbx/o365client"
	reflect "reflect"

	models "github.com/microsoftgraph/msgraph-sdk-go/models"
	gomock "go.uber.org/mock/gomock"
)

// MockFileHandlerInterface is a mock of FileHandlerInterface interface.
type MockFileHandlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockFileHandlerInterfaceMockRecorder
	isgomock struct{}
}

// MockFileHandlerInterfaceMockRecorder is the mock recorder for MockFileHandlerInterface.
type MockFileHandlerInterfaceMockRecorder struct {
	mock *MockFileHandlerInterface
}

// NewMockFileHandlerInterface creates a new mock instance.
func NewMockFileHandlerInterface(ctrl *gomock.Controller) *MockFileHandlerInterface {
	mock := &MockFileHandlerInterface{ctrl: ctrl}
	mock.recorder = &MockFileHandlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileHandlerInterface) EXPECT() *MockFileHandlerInterfaceMockRecorder {
	return m.recorder
}

// CreateWorkspace mocks base method.
func (m *MockFileHandlerInterface) CreateWorkspace() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkspace")
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWorkspace indicates an expected call of CreateWorkspace.
func (mr *MockFileHandlerInterfaceMockRecorder) CreateWorkspace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkspace", reflect.TypeOf((*MockFileHandlerInterface)(nil).CreateWorkspace))
}

// LoadState mocks base method.
func (m *MockFileHandlerInterface) LoadState(stateFilePath string) (*o365client.RunState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadState", stateFilePath)
	ret0, _ := ret[0].(*o365client.RunState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadState indicates an expected call of LoadState.
func (mr *MockFileHandlerInterfaceMockRecorder) LoadState(stateFilePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadState", reflect.TypeOf((*MockFileHandlerInterface)(nil).LoadState), stateFilePath)
}

// SaveAttachment mocks base method.
func (m *MockFileHandlerInterface) SaveAttachment(ctx context.Context, msgPath string, att models.Attachmentable, accessToken string, sequence int) (*filehandler.AttachmentMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAttachment", ctx, msgPath, att, accessToken, sequence)
	ret0, _ := ret[0].(*filehandler.AttachmentMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveAttachment indicates an expected call of SaveAttachment.
func (mr *MockFileHandlerInterfaceMockRecorder) SaveAttachment(ctx, msgPath, att, accessToken, sequence any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAttachment", reflect.TypeOf((*MockFileHandlerInterface)(nil).SaveAttachment), ctx, msgPath, att, accessToken, sequence)
}

// SaveAttachmentFromBytes mocks base method.
func (m *MockFileHandlerInterface) SaveAttachmentFromBytes(ctx context.Context, mailboxName, messageID, msgPath string, att models.Attachmentable, sequence int) ([]filehandler.AttachmentMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAttachmentFromBytes", ctx, mailboxName, messageID, msgPath, att, sequence)
	ret0, _ := ret[0].([]filehandler.AttachmentMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveAttachmentFromBytes indicates an expected call of SaveAttachmentFromBytes.
func (mr *MockFileHandlerInterfaceMockRecorder) SaveAttachmentFromBytes(ctx, mailboxName, messageID, msgPath, att, sequence any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAttachmentFromBytes", reflect.TypeOf((*MockFileHandlerInterface)(nil).SaveAttachmentFromBytes), ctx, mailboxName, messageID, msgPath, att, sequence)
}

// SaveError mocks base method.
func (m *MockFileHandlerInterface) SaveError(msgPath string, errs []error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveError", msgPath, errs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveError indicates an expected call of SaveError.
func (mr *MockFileHandlerInterfaceMockRecorder) SaveError(msgPath, errs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveError", reflect.TypeOf((*MockFileHandlerInterface)(nil).SaveError), msgPath, errs)
}

// SaveMessage mocks base method.
func (m *MockFileHandlerInterface) SaveMessage(message models.Messageable, bodyContent any, convertBody string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMessage", message, bodyContent, convertBody)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveMessage indicates an expected call of SaveMessage.
func (mr *MockFileHandlerInterfaceMockRecorder) SaveMessage(message, bodyContent, convertBody any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMessage", reflect.TypeOf((*MockFileHandlerInterface)(nil).SaveMessage), message, bodyContent, convertBody)
}

// SaveState mocks base method.
func (m *MockFileHandlerInterface) SaveState(state *o365client.RunState, stateFilePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveState", state, stateFilePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveState indicates an expected call of SaveState.
func (mr *MockFileHandlerInterfaceMockRecorder) SaveState(state, stateFilePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveState", reflect.TypeOf((*MockFileHandlerInterface)(nil).SaveState), state, stateFilePath)
}

// SaveStatusReport mocks base method.
func (m *MockFileHandlerInterface) SaveStatusReport(mailboxName string, sourceCounts map[string]int32, processedCount, errorCount int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveStatusReport", mailboxName, sourceCounts, processedCount, errorCount)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveStatusReport indicates an expected call of SaveStatusReport.
func (mr *MockFileHandlerInterfaceMockRecorder) SaveStatusReport(mailboxName, sourceCounts, processedCount, errorCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveStatusReport", reflect.TypeOf((*MockFileHandlerInterface)(nil).SaveStatusReport), mailboxName, sourceCounts, processedCount, errorCount)
}

// WriteAttachmentsToMetadata mocks base method.
func (m *MockFileHandlerInterface) WriteAttachmentsToMetadata(msgPath string, attachments []filehandler.AttachmentMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteAttachmentsToMetadata", msgPath, attachments)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteAttachmentsToMetadata indicates an expected call of WriteAttachmentsToMetadata.
func (mr *MockFileHandlerInterfaceMockRecorder) WriteAttachmentsToMetadata(msgPath, attachments any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteAttachmentsToMetadata", reflect.TypeOf((*MockFileHandlerInterface)(nil).WriteAttachmentsToMetadata), msgPath, attachments)
}
