// Code generated by MockGen. DO NOT EDIT.
// Source: o365mbx/o365client (interfaces: O365ClientInterface)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_o365client.go -package=mocks o365mbx/o365client O365ClientInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	o365client "o365mbx/o365client"
	reflect "reflect"

	models "github.com/microsoftgraph/msgraph-sdk-go/models"
	gomock "go.uber.org/mock/gomock"
)

// MockO365ClientInterface is a mock of O365ClientInterface interface.
type MockO365ClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockO365ClientInterfaceMockRecorder
	isgomock struct{}
}

// MockO365ClientInterfaceMockRecorder is the mock recorder for MockO365ClientInterface.
type MockO365ClientInterfaceMockRecorder struct {
	mock *MockO365ClientInterface
}

// NewMockO365ClientInterface creates a new mock instance.
func NewMockO365ClientInterface(ctrl *gomock.Controller) *MockO365ClientInterface {
	mock := &MockO365ClientInterface{ctrl: ctrl}
	mock.recorder = &MockO365ClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockO365ClientInterface) EXPECT() *MockO365ClientInterfaceMockRecorder {
	return m.recorder
}

// GetAttachmentRawStream mocks base method.
func (m *MockO365ClientInterface) GetAttachmentRawStream(ctx context.Context, mailboxName, messageID, attachmentID string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttachmentRawStream", ctx, mailboxName, messageID, attachmentID)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttachmentRawStream indicates an expected call of GetAttachmentRawStream.
func (mr *MockO365ClientInterfaceMockRecorder) GetAttachmentRawStream(ctx, mailboxName, messageID, attachmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttachmentRawStream", reflect.TypeOf((*MockO365ClientInterface)(nil).GetAttachmentRawStream), ctx, mailboxName, messageID, attachmentID)
}

// GetMailboxHealthCheck mocks base method.
func (m *MockO365ClientInterface) GetMailboxHealthCheck(ctx context.Context, mailboxName string) (*o365client.MailboxHealthStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMailboxHealthCheck", ctx, mailboxName)
	ret0, _ := ret[0].(*o365client.MailboxHealthStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMailboxHealthCheck indicates an expected call of GetMailboxHealthCheck.
func (mr *MockO365ClientInterfaceMockRecorder) GetMailboxHealthCheck(ctx, mailboxName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMailboxHealthCheck", reflect.TypeOf((*MockO365ClientInterface)(nil).GetMailboxHealthCheck), ctx, mailboxName)
}

// GetMailboxStats mocks base method.
func (m *MockO365ClientInterface) GetMailboxStats(ctx context.Context, mailboxName string) (map[string]int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMailboxStats", ctx, mailboxName)
	ret0, _ := ret[0].(map[string]int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMailboxStats indicates an expected call of GetMailboxStats.
func (mr *MockO365ClientInterfaceMockRecorder) GetMailboxStats(ctx, mailboxName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMailboxStats", reflect.TypeOf((*MockO365ClientInterface)(nil).GetMailboxStats), ctx, mailboxName)
}

// GetMessageAttachments mocks base method.
func (m *MockO365ClientInterface) GetMessageAttachments(ctx context.Context, mailboxName, messageID string) ([]models.Attachmentable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageAttachments", ctx, mailboxName, messageID)
	ret0, _ := ret[0].([]models.Attachmentable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageAttachments indicates an expected call of GetMessageAttachments.
func (mr *MockO365ClientInterfaceMockRecorder) GetMessageAttachments(ctx, mailboxName, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageAttachments", reflect.TypeOf((*MockO365ClientInterface)(nil).GetMessageAttachments), ctx, mailboxName, messageID)
}

// GetMessageDetailsForFolder mocks base method.
func (m *MockO365ClientInterface) GetMessageDetailsForFolder(ctx context.Context, mailboxName, folderName string, detailsChan chan<- o365client.MessageDetail) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageDetailsForFolder", ctx, mailboxName, folderName, detailsChan)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetMessageDetailsForFolder indicates an expected call of GetMessageDetailsForFolder.
func (mr *MockO365ClientInterfaceMockRecorder) GetMessageDetailsForFolder(ctx, mailboxName, folderName, detailsChan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageDetailsForFolder", reflect.TypeOf((*MockO365ClientInterface)(nil).GetMessageDetailsForFolder), ctx, mailboxName, folderName, detailsChan)
}

// GetMessages mocks base method.
func (m *MockO365ClientInterface) GetMessages(ctx context.Context, mailboxName, sourceFolderID string, state *o365client.RunState, messagesChan chan<- models.Messageable) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessages", ctx, mailboxName, sourceFolderID, state, messagesChan)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetMessages indicates an expected call of GetMessages.
func (mr *MockO365ClientInterfaceMockRecorder) GetMessages(ctx, mailboxName, sourceFolderID, state, messagesChan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessages", reflect.TypeOf((*MockO365ClientInterface)(nil).GetMessages), ctx, mailboxName, sourceFolderID, state, messagesChan)
}

// GetOrCreateFolderIDByName mocks base method.
func (m *MockO365ClientInterface) GetOrCreateFolderIDByName(ctx context.Context, mailboxName, folderName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateFolderIDByName", ctx, mailboxName, folderName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateFolderIDByName indicates an expected call of GetOrCreateFolderIDByName.
func (mr *MockO365ClientInterfaceMockRecorder) GetOrCreateFolderIDByName(ctx, mailboxName, folderName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateFolderIDByName", reflect.TypeOf((*MockO365ClientInterface)(nil).GetOrCreateFolderIDByName), ctx, mailboxName, folderName)
}

// MoveMessage mocks base method.
func (m *MockO365ClientInterface) MoveMessage(ctx context.Context, mailboxName, messageID, destinationFolderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveMessage", ctx, mailboxName, messageID, destinationFolderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MoveMessage indicates an expected call of MoveMessage.
func (mr *MockO365ClientInterfaceMockRecorder) MoveMessage(ctx, mailboxName, messageID, destinationFolderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveMessage", reflect.TypeOf((*MockO365ClientInterface)(nil).MoveMessage), ctx, mailboxName, messageID, destinationFolderID)
}
