// Code generated by MockGen. DO NOT EDIT.
// Source: o365mbx/emailprocessor (interfaces: EmailProcessorInterface)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_emailprocessor.go -package=mocks o365mbx/emailprocessor EmailProcessorInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmailProcessorInterface is a mock of EmailProcessorInterface interface.
type MockEmailProcessorInterface struct {
	ctrl     *gomock.Controller
	recorder *MockEmailProcessorInterfaceMockRecorder
	isgomock struct{}
}

// MockEmailProcessorInterfaceMockRecorder is the mock recorder for MockEmailProcessorInterface.
type MockEmailProcessorInterfaceMockRecorder struct {
	mock *MockEmailProcessorInterface
}

// NewMockEmailProcessorInterface creates a new mock instance.
func NewMockEmailProcessorInterface(ctrl *gomock.Controller) *MockEmailProcessorInterface {
	mock := &MockEmailProcessorInterface{ctrl: ctrl}
	mock.recorder = &MockEmailProcessorInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailProcessorInterface) EXPECT() *MockEmailProcessorInterfaceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockEmailProcessorInterface) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockEmailProcessorInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEmailProcessorInterface)(nil).Close))
}

// Initialize mocks base method.
func (m *MockEmailProcessorInterface) Initialize(ctx context.Context, chromiumPath string, poolSize int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialize", ctx, chromiumPath, poolSize)
	ret0, _ := ret[0].(error)
	return ret0
}

// Initialize indicates an expected call of Initialize.
func (mr *MockEmailProcessorInterfaceMockRecorder) Initialize(ctx, chromiumPath, poolSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockEmailProcessorInterface)(nil).Initialize), ctx, chromiumPath, poolSize)
}

// IsHTML mocks base method.
func (m *MockEmailProcessorInterface) IsHTML(content string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsHTML", content)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsHTML indicates an expected call of IsHTML.
func (mr *MockEmailProcessorInterfaceMockRecorder) IsHTML(content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsHTML", reflect.TypeOf((*MockEmailProcessorInterface)(nil).IsHTML), content)
}

// ProcessBody mocks base method.
func (m *MockEmailProcessorInterface) ProcessBody(ctx context.Context, htmlContent, convertBody string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessBody", ctx, htmlContent, convertBody)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessBody indicates an expected call of ProcessBody.
func (mr *MockEmailProcessorInterfaceMockRecorder) ProcessBody(ctx, htmlContent, convertBody any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessBody", reflect.TypeOf((*MockEmailProcessorInterface)(nil).ProcessBody), ctx, htmlContent, convertBody)
}
